### PR TITLE
fix: backward jump type context compatibility check

### LINKED ISSUE #9: Bug in compatibility check in Tier 2 backwards jump, leading to execution of incompatible BB
## The bug

As mentioned in #3, since the compatibility check in the type context only checks if the type each node resolves to is compatible, the underlying type trees can be different which potentially causes the executed BB to be incompatible.

Suppose we have the following loop like this:
```mermaid
graph TD;
  A[A: type check on first element of stack] --> B;
  B --> A;
```
Suppose the first time encountering `A` our type context is:
```
type context A1
locals: [?, ?]
stack: [?->locals[0]]
```
Suppose we type check the `?` on the stack which happens to be an `int`, resulting in the following type context:
```
type context A1'
locals: [int, ?]
stack: [int->locals[0]]
```
The BB `B` is then generated assuming type context `A1'`. Suppose after executing `B` we jump back to `A` with the following type context:
```
type context A2
locals: [?, ?]
stack: [?->locals[1]]
```
Type context `A2` is compatible with `A1` with the current compatibility check, so we don't emit a new version of BB `A`. Suppose type check of the `?` on the stack passes again. We end up with:
```
type context A2'
locals: [?, int]
stack: [int->locals[1]]
```
Since the check passes, we jump to the already generated BB `B`. However, BB `B` is generated with the assumption that `locals[0]` is an `int` (type context `A1'`). This could result in executing code that results in a type error, or potentially a crash if the object has been unboxed.

## Potential fixes

A potential way to fix this is to not only check the compatibility of the resolved types but also the compatibility of the type trees. Such "compatibility criterion" could be:
> `ctx1` is _compatible_ with `ctx2` if any execution state with `ctx1` can run on code emitted from `ctx2`.

Since emitting the next opcode is entirely dependent on the current tier1 bytecode (fixed for both ctx1 and ctx2) and the type context at that bytecode (might not be the same), the criterion is probably equivalent to 
> `ctx1` is _compatible_ with `ctx2` if:
>  1. The partition induced by the type trees in `ctx2` is a **refinement** of the partition induced in `ctx1`.
>  2. Each node in `ctx1` resolves to a type compatible with the resolved type of the corresponding node in `ctx2`.

We can call `ctx2` a **refinement** of `ctx1` under this criterion.

As this condition will ensure that for all type operations `OVERWRITE`, `SET` and `SWAP`, the resulting type context `ctx1'` after executing a type operation will have nodes that resolve to a type compatible with the resolved type of the corresponding node in `ctx2'`.

However, it might not be beneficial to use this criterion, rather we can use a less general criterion:
> `ctx1` is _exactly compatible_ with `ctx2` if: 
> 1. The partition induced by the type trees in `ctx2` is **equivalent** to the partition induced in `ctx1`.
> 2. Each node in `ctx1` resolves to a type compatible with the resolved type of the corresponding node in `ctx2`.

We can call `ctx2` a **strict refinement** of `ctx1` if `ctx1` is _compatible_ with `ctx2` but not _exactly compatible_.

Using the _exactly compatible_ criterion might be desirable as if `ctx2` **strictly refines** `ctx1`, code-gen by `ctx1` might be more type specialised than `ctx2`, resulting in potentially more efficient code, since a `TYPE_SET` operation on a larger tree will resolve more nodes.

My personal opinion is to go with the less general criterion.

### PR DESCRIPTION
**Pull request by Fidget-Spinner**
Closes https://github.com/pylbbv/pylbbv/issues/9

### CODE REVIEW

File: Python/tier2.c [hunk 1]
```diff
@@ -2649,6 +2649,78 @@ _PyTier2_GenerateNextBB(
...
 }
 
+/**
+ * @brief Helper funnction of typecontext_is_compatible. See that for why we need this.
+ * @param ctx1_node A type node belong to a type context.
+ * @param ctx2_node A type node beloning to a different type context.
+ * @return If the type nodes' parent trees are compatible.
+*/
+static bool
+typenode_is_compatible(_Py_TYPENODE_t ctx1_node, _Py_TYPENODE_t ctx2_node)
```
Comment (JuliaPoo) [inline Python/tier2.c]: This is too strict. The trees might form the same partition but have a different structure (e.g., different root).

Comment (JuliaPoo) [reply Python/tier2.c]: Hmm I'll commit a fix

Comment (Fidget-Spinner) [reply Python/tier2.c]: See https://github.com/pylbbv/pylbbv/issues/9#issuecomment-1574805186 for my reasoning.

Comment (JuliaPoo) [reply Python/tier2.c]: Oh yea i saw the comment, is just that, your code doesn't account for when the trees look different. E.g.,
```py
stack: [?->locals[0]]
locals: [?]

stack: [?]
locals: [?->stack[0]]
```
These two contexts should be equivalent, but won't be passed by your check

Comment (Fidget-Spinner) [reply Python/tier2.c]: I don't think those two contexts are equivalent. Using your example as a counterexample, for the first type context if we assign locals to be int, then stack will be int, but in the second example, assigning locals to be int should not affect the stack.

The relationship is unidirectional and we shouls respect that in the code.

Comment (JuliaPoo) [reply Python/tier2.c]: But in all the type operations, in effect we should be thinking of the type trees as a convenient way of thinking of a partition of the type contexts into nodes that have the same type. We should be matching the partitions rather than the structure of the trees.

E.g., suppose we `TYPE_SET` the locals in the second example, wouldn't that also imply `stack[0]` should resolve to an `int`? Suppose instead we `TYPE_OVERWRITE`, then `locals[0]` becomes it's own tree and `stack[0]` isn't touched.

**Comment by JuliaPoo** [comment]
I've committed the code to match partitions, do review and merge if it's okay~

**Comment by JuliaPoo** [comment]
We should replace `diff_typecontext`  with the corresponding compatibility function since we are matching the types exactly now.
And we should modify `_PyTier2_LocateJumpBackwardsBB` to early terminate.

**Comment by Fidget-Spinner** [comment]
> We should replace `diff_typecontext` with the corresponding compatibility function since we are matching the types exactly now. And we should modify `_PyTier2_LocateJumpBackwardsBB` to early terminate.

Shouldn't we modify `diff_typecontext` instead of to diff assuming the partitions are the same but the roots are widened?

E.g. same partition, but ctx1 points to NULL, then ctx2 points to INT. Shouldn't we allow that since ctx2->ctx1 is safe?

**Comment by JuliaPoo** [comment]
Ahh if so then I misunderstood the original fix. In the original fix you did:
```c
return (tag1 == TYPE_ROOT && tag2 == TYPE_ROOT) &&
        ((PyTypeObject *)_Py_TYPENODE_CLEAR_TAG(ref1) ==
        (PyTypeObject *)_Py_TYPENODE_CLEAR_TAG(ref2));
```

Which effectively forces the types to be equals. I reasoned that you might have wanted this in order to generate more efficient code.

**Comment by Fidget-Spinner** [comment]
> Ahh if so then I misunderstood the original fix. In the original fix you did:
> 
> ```c
> return (tag1 == TYPE_ROOT && tag2 == TYPE_ROOT) &&
>         ((PyTypeObject *)_Py_TYPENODE_CLEAR_TAG(ref1) ==
>         (PyTypeObject *)_Py_TYPENODE_CLEAR_TAG(ref2));
> ```
> 
> Which effectively forces the types to be equals. I reasoned that you might have wanted this in order to generate more efficient code.

Oh woops I forgot that. Yup I need to use the diffing function here instead.

**Comment by JuliaPoo** [comment]
Okie I've committed the changes. Just a comment, this fixes a weird type error when running `help(1)`, but now it stackoverflows. I attempted to triage this issue but it's close to impossible given how complex `help(1)` is.

**Comment by Fidget-Spinner** [comment]
Debug trace output for help(1)

image

**Comment by Fidget-Spinner** [comment]
> Okie I've committed the changes. Just a comment, this fixes a weird type error when running `help(1)`, but now it stackoverflows. I attempted to triage this issue but it's close to impossible given how complex `help(1)` is.

Ok we'll fix that in https://github.com/pylbbv/pylbbv/issues/15. I suspect it might be due to https://github.com/pylbbv/pylbbv/issues/14.
