### PR TITLE
fix: wrong offset in `BB_BRANCH_IF_FLAG_SET` codegen

### LINKED ISSUE #18: Crash possibly in handling of `FOR_ITER`
## POC
```py
def f(x,l):
    for _ in l:
        _
    x+x # Force it to be optimisable

for i in range(64): f(i, [])
f(i, [0])
```

## Log
```
>>> f(i, [0])
  [*] Copying type context
      Stack: 00000231FA0FD420: [ ? ?]
      Locals 00000231FA0FD3F0: [ ? ? ?]
offset: 10
  [-] Type stack bef: 2
  [-] Type propagating across: LOAD_FAST : 0
  [-] Type stack aft: 3
      Stack: 00000231FA0FD630: [ ? ?]
      Locals 00000231FA0FD5D0: [ ? ? ?]
offset: 11
  [-] Type stack bef: 3
  [-] Type propagating across: LOAD_FAST : 0
Fatal Python error: typenode_is_same_tree: We've reached an unreachable state. Anything is possible.
The limits were in our heads all along. Follow your dreams.
https://xkcd.com/2200
Python runtime state: initialized

Current thread 0x00006d2c (most recent call first):
  File "<stdin>", line 3 in f
  File "<stdin>", line 1 in <module>
```

### PR DESCRIPTION
**Pull request by JuliaPoo**
Closes #18

### CODE REVIEW

File: Python/bytecodes.c [hunk 1]
```diff
@@ -3355,10 +3355,10 @@ dummy_func(
                 _Py_CODEUNIT *t2_nextinstr = NULL;
                 _PyBBBranchCache *cache = (_PyBBBranchCache *)next_instr;
                 _Py_CODEUNIT *tier1_fallback = NULL;
-
                 t2_nextinstr = _PyTier2_GenerateNextBB(
                     frame, cache->bb_id_tagged, next_instr - 1,
-                    oparg, &tier1_fallback, bb_test);
+                //  v We generate from the tier1 successor BB, so offset is 0.
```
Comment (Fidget-Spinner) [inline Python/bytecodes.c]: /s/successor/consequent because successor is technically the alternative BB at this point.
```suggestion
                //  v   We generate from the tier1 consequent BB, so offset (oparg) is 0.
```

**Review by Fidget-Spinner — APPROVED** [review]
